Reordered and updated

diff --git a/start_scripts/startlxqtlabwc b/start_scripts/startlxqtlabwc
--- a/start_scripts/startlxqtlabwc
+++ b/start_scripts/startlxqtlabwc
@@ -36,7 +36,6 @@ if [ -z "$XDG_CACHE_HOME" ]; then
     export XDG_CACHE_HOME="$HOME/.cache"
 fi
 
-
 # Ensure the existence of the 'Desktop' folder
 if [ -e "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
     . "$XDG_CONFIG_HOME/user-dirs.dirs"
@@ -45,35 +44,44 @@ else
 fi
 mkdir -p "$XDG_DESKTOP_DIR"
 
-
 # Launch DBus if needed
 if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
     if [ -z "$XDG_RUNTIME_DIR" ] || ! [ -S "$XDG_RUNTIME_DIR/bus" ] || ! [ -O "$XDG_RUNTIME_DIR/bus" ]; then
-        eval "$(dbus-launch --sh-syntax --exit-with-session)" || echo "startlxqtwayfire: error executing dbus-launch" >&2
+        eval "$(dbus-launch --sh-syntax --exit-with-session)" || echo "startlxqt: error executing dbus-launch" >&2
     fi
 fi
 
 # Qt4 platform plugin
-export QT_PLATFORM_PLUGIN=lxqt
+export QT_PLATFORM_PLUGIN="lxqt"
 
 # Qt5 platform plugin
-export QT_QPA_PLATFORMTHEME=lxqt
+export QT_QPA_PLATFORMTHEME="lxqt"
+
+# use lxqt-applications.menu for main app menu
+export XDG_MENU_PREFIX="lxqt-"
+
 export XDG_CURRENT_DESKTOP="LXQt"
-export XDG_SESSION_DESKTOP="LXQt"
 
-# Export language setting and scale factor
-# To do: script for readiing and exporting most of session.conf [Environment]
+# Import compositor from  LXQt settings:
+#export $(cat $XDG_CONFIG_HOME/lxqt/session.conf |grep wayland_compositor)
+export wayland_compositor=labwc
 
+# Import and set locale and scale factor from lxqt (not needed if using lxqt-session)
 export $(cat "$XDG_CONFIG_HOME"/lxqt/lxqt-config-locale.conf |grep LANG)
 export $(cat "$XDG_CONFIG_HOME"/lxqt/session.conf |grep QT_SCALE_FACTOR)
-
-## End LXQt common settings
-
-export MOZ_ENABLE_WAYLAND=1
 
 # Faster startup for GTK applications
 dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY
 
-# Start the LXQt Wayland session
+# Firefox
+export MOZ_ENABLE_WAYLAND=1
 
-exec wayfire -c "$XDG_CONFIG_HOME"/lxqt/lxqt-wayfire/wayfire.ini
+# Grim (screenshots)
+#export GRIM_DEFAULT_DIR=/tmp
+
+# Create wayland settings dir if not existing
+mkdir -p -- "$XDG_CONFIG_HOME/lxqt-wayland"
+
+# Start the compositor
+exec labwc -C $XDG_CONFIG_HOME/lxqt-wayland/labwc
+
